language: c

sudo: required

os:
  - linux

env:
  - OCAML_VERSION=4.02

before_install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
  - wget http://www.ferzkopp.net/Software/SDL2_gfx/SDL2_gfx-1.0.3.tar.gz

install:
  - bash -ex .travis-ocaml.sh
  - bash -ex install-llvm.sh
  - bash -ex install-sdl-gfx.sh

before_script:
  - eval `opam config env`
  - sudo apt install --yes xvfb
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - xvfb -screen 0 1024x768x24

script:
  - make clean all
  - ./testall.sh
  - cat testall.log

notifications:
  email: false
