language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
os:
  - linux
env:
  - OCAML_VERSION=4.02
script:
  - bash -ex .travis-ocaml.sh
  - make clean dep scanner.ml parser.ml
notifications:
  email: false
