language: c

sudo: required

install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh

os:
  - linux

env:
  - OCAML_VERSION=4.02

before_script:
  - bash -ex .travis-ocaml.sh
  - bash -ex install-llvm.sh
  - eval `opam config env` 

script:
  - make clean scanner.ml parser.ml sol
  - ./testall.sh

notifications:
  email: false
