language: c

sudo: required

os:
  - linux

env:
  - OCAML_VERSION=4.02

before_install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
  - wget http://www.ferzkopp.net/Software/SDL2_gfx/SDL2_gfx-1.0.3.tar.gz

install:
  - bash -ex install-sdl-gfx.sh
  - bash -ex .travis-ocaml.sh
  - bash -ex install-llvm.sh

before_script:
  - eval `opam config env` 

script:
  - make clean all
  - ./testall.sh

notifications:
  email: false
