# @author: Kunal Baweja

# Make sure ocamlbuild can find opam-managed packages: first run
# eval `opam config env`
# Easiest way to build: using ocamlbuild, which in turn uses ocamlfind

CC = gcc
CFLAGS = -std=c99 -O2 -D_REENTRANT -I/usr/include/SDL2
LIBS = 
LFLAGS = -lSDL2 -lSDL2_gfx -lm

all : sol.native predefined.o

sol.native:
	ocamlbuild -use-ocamlfind -pkgs llvm,llvm.analysis -cflags -w,+a-4 \
		sol.native

sol.d.byte:
	ocamlbuild -use-ocamlfind -pkgs llvm,llvm.analysis -cflags -w,+a-4 \
		sol.d.byte

# "make clean" removes all generated files

.PHONY : clean

clean:
	ocamlbuild -clean
	rm -rf testall.log *.diff sol scanner.ml parser.ml parser.mli
	rm -rf *.cmx *.cmi *.cmo *.cmx *.o *.s *.ll *.out *.exe *.err *.diff

# More detailed: build using ocamlc/ocamlopt + ocamlfind to locate LLVM

OBJS = ast.cmx codegen.cmx parser.cmx scanner.cmx semant.cmx sol.cmx 

sol: $(OBJS)
	ocamlfind ocamlopt -linkpkg -package llvm -package llvm.analysis $(OBJS) -o sol

scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<

%.cmx : %.ml
	ocamlfind ocamlopt -c -package llvm $<

predefined.o: predefined.c
	$(CC) -c $^ $(CFLAGS) $(LIBS) $(LFLAGS)

# Testing the "bindings" example

### Generated by "ocamldep *.ml *.mli" after building scanner.ml and parser.ml
ast.cmo :
ast.cmx :
codegen.cmo : ast.cmo
codegen.cmx : ast.cmx
sol.cmo : semant.cmo scanner.cmo parser.cmi codegen.cmo ast.cmo
sol.cmx : semant.cmx scanner.cmx parser.cmx codegen.cmx ast.cmx
parser.cmo : ast.cmo parser.cmi
parser.cmx : ast.cmx parser.cmi
scanner.cmo : parser.cmi
scanner.cmx : parser.cmx
semant.cmo : ast.cmo
semant.cmx : ast.cmx
parser.cmi : ast.cmo
